### ISSUE TITLE
Preview embed disappears on website

### ISSUE THREAD

**Issue by jonmalave** [shobhitsharma/embedo#1]
Embedo library seems pretty cool, although the preview on the website doesn't seem to work very well... At least not on Chrome browser that I tried on. When I enter the URL of say http://twitter.com/jonmalave the preview renders the width OK, but doesn't render the height correctly, then within seconds disappears. So it's not allowing me to preview what the embed would look like really...

**Comment by shobhitsharma** [comment]
![screen shot 2017-02-13 at 11 58 08 pm](https://cloud.githubusercontent.com/assets/772855/22907216/50e053da-f248-11e6-9604-630065d60c2b.png)

embedo is ideally meant to embed tweets, since you are trying to embed entire timeline here, its scaling and got transformed to bottom. In example, I haven't added any limits as such, but it deserves a scrollbar definitely. But you can adjust your case using `.watch` event from the docs to adjust when you implement it.

I'll find a solution for this odd case. Thanks for the report.

**Comment by shobhitsharma** [comment]
Sorted scaling issue. Whole timeline is embedded using oembed, so while hooking, make sure to apply `overflow-scroll` limit with suitable height for your container.
